# Generated by Django 3.0.7 on 2020-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('aadhar', models.IntegerField()),
                ('fname', models.CharField(max_length=60)),
                ('foccupation', models.CharField(max_length=60)),
                ('institutename', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=60)),
                ('presentyear', models.CharField(max_length=60)),
                ('percentage12', models.CharField(max_length=60)),
                ('cgpa', models.CharField(max_length=60)),
                ('photograph', models.ImageField(default='', upload_to='Photograph')),
                ('marksheet12', models.FileField(default='', upload_to='Marksheet_12')),
                ('lmarksheet', models.FileField(default='', upload_to='Latest_Marksheet')),
                ('bletter', models.FileField(default='', upload_to='Bonafied_Letter')),
                ('Designation', models.CharField(default='', max_length=60)),
                ('CPF', models.CharField(default='', max_length=60)),
                ('Section', models.CharField(default='', max_length=60)),
                ('Location', models.CharField(default='', max_length=60)),
                ('PhoneNumber', models.IntegerField(default=0)),
                ('MobileNumber', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
