# Generated by Django 3.0.7 on 2020-06-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ongc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
