# Generated by Django 3.0.7 on 2020-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ongc', '0002_auto_20200630_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='MobileNumber',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='regform',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
