# Generated by Django 3.0.7 on 2020-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_ongc', '0003_auto_20200630_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='CPF',
            field=models.CharField(default='NULL', max_length=60),
        ),
        migrations.AlterField(
            model_name='regform',
            name='Designation',
            field=models.CharField(default='NULL', max_length=60),
        ),
        migrations.AlterField(
            model_name='regform',
            name='Location',
            field=models.CharField(default='NULL', max_length=60),
        ),
        migrations.AlterField(
            model_name='regform',
            name='MobileNumber',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AlterField(
            model_name='regform',
            name='PhoneNumber',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AlterField(
            model_name='regform',
            name='Section',
            field=models.CharField(default='NULL', max_length=60),
        ),
    ]
